### ISSUE TITLE
data Attribute - zusätzliches Eingabefeld

### ISSUE THREAD

**Issue by saress** [DMAGmbH/dma_simple_grid#14]
Hallo Janosch,

wir verwenden als Framework ja in den allermeisten Fällen Foundation und hier ist es oftmals erforderlich verschiedenste data-Attribute zu ergänzen, z. B.:

`<div class="row medium-collapse" data-equalizer data-equalize-on="medium">`

Daher wäre es perfekt, wenn es für die einzelnen Elemente (wrapper, row, columns) jeweils analog zu den CSS/ID Eingabefeldern ein weiteres geben würde, wo solche Zusatz-Tags eingegeben werden können, damit diese dann wie im Beispiel oben ausgegeben werden können.

Vielen Dank und beste Grüße
Saress

**Comment by saress** [comment]
Danke Janosch!

**Comment by JanoschOltmanns** [comment]
Für Data-Attribute empfehle ich gerne: https://extensions.contao.org/?p=janoscholtmanns%2Fcontao-data-attributes-bundle
