### ISSUE TITLE
Gridnutzung bei inkludierten Elementen

### ISSUE THREAD

**Issue by sascha-mueller** [DMAGmbH/dma_simple_grid#16]
Beim Versuch include-Elemente, wie referenzierte CEs, Formulare oder Module mit den vorkonfigurierten Gridklassen zu versehen, werden dieses zwar im Backend gespeichert, jedoch im Frontend nicht ausgegeben.

**Comment by stefanschleich** [comment]
Habe ich auch festgestellt. Gibt es dafür eine Lösung oder ist diese Extension stillgelegt?

**Comment by JanoschOltmanns** [comment]
@stefanschleich bisher gibt es dafür noch keine Lösung. Wir gucken aber mal, ob wir eine Möglichkeit finden.

**Comment by JanoschOltmanns** [comment]
@stefanschleich @sascha-mueller mögt ihr dieses Verhalten im develop-Branch einmal testen? Bitte beachten, dass das Verhalten erst in den Einstellungen aktiviert werden muss.

**Comment by stefanschleich** [comment]
@JanoschOltmanns Habe es gerade getestet (Contao 4.4.3). Bei einem inkludierten Inhaltselement vom Typ Text klappt es wie gewünscht. Bei einem inkludierten Formular fehlen die Klassen. Die am Include-Element von Hand zugewiesene CSS-Klasse über das Standardfeld ist da, die Raster-Klassen jedoch nicht.

**Comment by stefanschleich** [comment]
Hast du dir das noch mal angeschaut, @JanoschOltmanns? Mir ist dazu noch aufgefallen, dass bei inkludierten Frontend-Modulen (anders als bei Formularen) die Grid-Felder gar nicht ausgegeben werden. In meinem Fall bei einem Nachrichtenliste-Modul. Ich weiß allerdings nicht, ob das an deinen Änderungen im develop-Branch liegt oder ob die Felder bei include-Modulen auch vorher schon nicht vorhanden waren.

**Comment by Aybee** [comment]
>@stefanschleich  ...dass bei inkludierten Frontend-Modulen (anders als bei Formularen) die Grid-Felder gar nicht ausgegeben werden.

Dies fehlt mir auch gerade für eingebundene FE-Module. Es ist hier deaktiviert:
https://github.com/DMAGmbH/dma_simple_grid/blob/1.0.0/src/dma_simple_grid/classes/DmaSimpleGridDcaCallbacks.php#L138

Ich patche jetzt die Core-Datei, weil ich nicht weiß, wie ich dies nachträglich anpassen soll, ohne die Funktion noch mal neu aufzusetzen.

Ein **Feature-Request** wäre also, entweder die CEs `module` **nicht** auszuschließen, oder in den Settings eine Komma getrennte Liste eingeben zu können, über welche man bestimmte CEs ausschließen kann.

**Comment by Aybee** [comment]
Ah, ok, ich sehe. Die Gridauswahl ist dann zwar dort im CE `module` vorhanden, aber aber man muss noch daran schrauben, dass die Klassen auch in die Module-Templates kommen. Bei diesen Include-CEs fehlt ja der mod_article-Wrapper und es scheint so, als würden die Klassen momentan nur auf diese mod_article-Templates aufgesetzt.

**Comment by JanoschOltmanns** [comment]
Genau das ist aktuell das Problem. Ich gucke noch mal, ob mir was sinnvolles einfällt.

**Comment by Aybee** [comment]
Also ich habe gesehen, dass dort im CE `module` das Feld `cssID` ist. Eine dort eingetragene Klasse wird irgendwie zu den Klassen des Modul-Wrappers hinzugefügt. Jetzt müsste man herausfinden wie Contao das macht und versuchen dies mit den Grid-Klassen genauso zu machen.
