### ISSUE TITLE
push latest version to packagist.org

### ISSUE THREAD

**Issue by markocupic** [DMAGmbH/dma_simple_grid#18]
Hi Janosch
Thank you for your great work on this extension. Could you push the latest version (bootstrap-alpha-4.0.0-.6) compat version) to packagist.org? So I can use it with composer.
Kind regards
Marko

**Comment by markocupic** [comment]
Thank you!
Kind Regards
Marko

**Comment by stefanschleich** [comment]
The version at packagist.org again differs from the repo. Could you please update it?

Thanks a lot,
Stefan
