### ISSUE TITLE
getestet in Contao 4

### ISSUE THREAD

**Issue by kgansberger** [DMAGmbH/dma_simple_grid#23]
Zur Info: Funktioniert prima in den Artikel, im Formular allerdings wird das Backendlayout zerschossen sobald columns dazu generiert werden.

Ja, ich weiss, ist nicht für c4 frei gegeben :)

**Comment by JanoschOltmanns** [comment]
Welche Version und wann geladen? Die 1.0.0 von gestern?

**Comment by kgansberger** [comment]
Nein, probiere ich gleich!

**Comment by kgansberger** [comment]
perfekt, danke!
