### ISSUE TITLE
Flexbox als Grid in Simple Grid?

### ISSUE THREAD

**Issue by jscholtysik** [DMAGmbH/dma_simple_grid#3]
Hi,

auf http://gridlex.devlint.fr/ hat sich jemand schon mal Gedanken gemacht, wie man das Flexbox Layout in ein Grid verpacken könnte? Wäre sowas auch in Simple Grid integrierbar?

Viele Grüße.

Joachim

**Comment by JanoschSkuplik** [comment]
Hallo Joachim,

das schaue ich mir gerne mal an.

Danke!

**Comment by JanoschOltmanns** [comment]
Siehe auch https://github.com/DMAGmbH/dma_simple_grid/issues/9

**Comment by JanoschOltmanns** [comment]
Werde diese in https://github.com/DMAGmbH/dma_simple_grid/issues/9 und https://github.com/DMAGmbH/dma_simple_grid/issues/10 weiter verfolgen.
