### ISSUE TITLE
offset-right (suffix) will not work for unsemantic

### ISSUE THREAD

**Issue by Aybee** [DMAGmbH/dma_simple_grid#4]
Es fehlen ein paar Zeilen in der https://github.com/DMAGmbH/dma_simple_grid/blob/master/src/dma_simple_grid/classes/DmaSimpleGrid.php
Zeile 94+

``` php
if (!is_array($arrTemplateData['dma_simplegrid_offsetrightsettings'])) {
    $arrOffsetRightSettings = deserialize($arrTemplateData['dma_simplegrid_offsetrightsettings'], true);
}
```

Zeile 122+

``` php
if (sizeof($arrOffsetRightSettings) == 1 && $GLOBALS['TL_CONFIG']['dmaSimpleGrid_useOffsetRight']) {
    $arrElementSettings = $arrOffsetRightSettings[0];
    if (is_array($arrElementSettings)) {
        foreach ($arrElementSettings as $columnKey => $varValue) {
            if ($varValue) {
                $arrConfiguredClasses[] = sprintf(static::$arrCache['grid']['config']['columns-config'][$columnKey]['offset-right-class'], $varValue);
            }
        }
    }
}
```

Zeile 252+

``` php
if (!is_array($arrRow['dma_simplegrid_offsetrightsettings'])) {
    $arrOffsetRightSettings = deserialize($arrRow['dma_simplegrid_offsetrightsettings'], true);
}
```

Zeile 285+

``` php
if (sizeof($arrOffsetRightSettings) == 1 && $GLOBALS['TL_CONFIG']['dmaSimpleGrid_useOffsetRight']) {
    $arrElementSettings = $arrOffsetRightSettings[0];
    if (is_array($arrElementSettings)) {
        foreach ($arrElementSettings as $columnKey => $varValue) {
            if ($varValue && static::$arrCache['grid']['config']['columns-config'][$columnKey]['name']) {
                $arrConfiguredClasses[] = static::$arrCache['grid']['config']['columns-config'][$columnKey]['name'] . "-offset-right: " . $varValue;
            }
        }
    }
}
```

Ich hoffe ich habe keinen Fehler gemacht und nichts vergessen.

**Comment by JanoschSkuplik** [comment]
Thx!

**Comment by Aybee** [comment]
Ich danke dir auch.
Btw. wäre es nicht übersichtlicher und weniger fehleranfällig, wenn du diese Sachen in einem foreach abarbeiten könntest? Z.B. das hier

``` php
if (!is_array($arrTemplateData['dma_simplegrid_columnsettings'])) {
    $arrColumnSettings = deserialize($arrTemplateData['dma_simplegrid_columnsettings'], true);
}
if (!is_array($arrTemplateData['dma_simplegrid_offsetsettings'])) {
    $arrOffsetSettings = deserialize($arrTemplateData['dma_simplegrid_offsetsettings'], true);
}
if (!is_array($arrTemplateData['dma_simplegrid_offsetrightsettings'])) {
    $arrOffsetRightSettings = deserialize($arrTemplateData['dma_simplegrid_offsetrightsettings'], true);
}
if (!is_array($arrTemplateData['dma_simplegrid_pushsettings'])) {
    $arrPushSettings = deserialize($arrTemplateData['dma_simplegrid_pushsettings'], true);
}
if (!is_array($arrTemplateData['dma_simplegrid_pullsettings'])) {
    $arrPullSettings = deserialize($arrTemplateData['dma_simplegrid_pullsettings'], true);
}
```

**Comment by JanoschSkuplik** [comment]
Auf jeden Fall. Aktuell ist das ganze noch in der Test-Phase. 

Die Strukturen werden noch einmal etwas überarbeitet, sobald die Anforderungen auf Grundlage der aktuellen User klarer sind. Viele der aktuell integrierten Sachen kamen nachträglich rein.

**Comment by Aybee** [comment]
Dann bin ich mal gespannt. Für mich scheint sich diese Erweiterung momentan als beste Wrapper-, Grid-Lösung herauszustellen. Bis jetzt habe ich semantic_html5, rocksolid-columns, subcolumns und diverse andere benutzt.

Evtl. könnte man die Bezeichnungen noch anpassen, bei unsemantic nennt sich der Offset z.B. "prefix" und der OffsetRight "suffix". Hat aber very low priority.

Sehr schade finde ich allerdings, dass sie nicht im ER1 zur Verfügung steht. Das wäre richtig super, wenn du sie dort noch einstellen könntest.

**Comment by JanoschSkuplik** [comment]
Sodele, damit steht die Erweiterung nun auch über das ER2 (dma_simple_grid) zur Verfügung. Auch per Composer sollte sie nun installierbar sein. Lediglich die Abhängigkeit zum MultiColumnWizard lässt sich da noch nicht korrekt für Contao 4.1 auflösen, wenn da wer Ideen hat – her damit ;)

**Comment by Aybee** [comment]
Wow, super. Tausend Dank. Das spart Arbeit. Habe ich gerade übers ER im ersten Projekt installiert. :satisfied:
