### ISSUE TITLE
Warning: Undefined array key "hasBlockGrid" , PHP8

### ISSUE THREAD

**Issue by kraustomas** [DMAGmbH/dma_simple_grid#43]
If you go under Contao to system administration on server with PHP8 and dma_simple_grid 1.1.0 installed there is message: Warning: Undefined array key "hasBlockGrid" in vendor/dma/dma_simple_grid/src/Resources/contao/classes/DmaSimpleGridDcaCallbacks.php:69

**Comment by think-digital-agency** [comment]
Im also getting the mentioned error message. Steps to reproduce:

1. use PHP 8
2. install newest dma_simple_grid Version 1.1.1
3. go to "Einstellungen" in Contao Backend

Is it possible to fix this? Would really be great. Right now its the only reason we can not use this helpful extension anymore.

<img width="1069" alt="Bildschirmfoto 2022-07-12 um 19 52 04" src="https://user-images.githubusercontent.com/6197911/178559997-57721c15-ac16-4078-b754-dd4840a76e1c.png">
<img width="1055" alt="Bildschirmfoto 2022-07-12 um 19 52 24" src="https://user-images.githubusercontent.com/6197911/178560021-78f305a4-87af-48f8-bf6d-2e50fe458ca8.png">

**Comment by JanoschOltmanns** [comment]
I will look at it tomorrow. But I think you could also check the other php 8 related pull request (https://github.com/DMAGmbH/dma_simple_grid/pulls?q=is%3Apr+is%3Aclosed) and try a fix.

**Comment by JanoschOltmanns** [comment]
Should be fixed with release 1.1.2 (https://github.com/DMAGmbH/dma_simple_grid/releases/tag/v1.1.2)
