### ISSUE TITLE
Für Contao 5.3 installierbar machen

### ISSUE THREAD

**Issue by MacKP** [DMAGmbH/dma_simple_grid#52]
Hi,
wäre super, wenn das ganze auch unter Contao 5.3 installierbar wäre ;-)

Viele Grüße

**Comment by JanoschOltmanns** [comment]
Teste bitte mal, ob die [2.0.0-alpha](https://github.com/DMAGmbH/dma_simple_grid/releases/tag/2.0.0-alpha) korrekt läuft. Da fehlt aktuell noch Feedback ;-)

**Comment by MacKP** [comment]
Cool. Danke. Mache ich ;-)

**Comment by think-digital-agency** [comment]
Hallo zusammen! Kann bestätigen dass die 2.0.0-alpha für mich sowohl unter Contao 5.3 als auch 5.4 läuft! Habe sie auf einigen Installationen erfolgreich im Einsatz (siehe bspw. https://contao-design-plus.think-digital.agency). Besten Dank!

**Comment by JanoschOltmanns** [comment]
Sollte mit https://github.com/DMAGmbH/dma_simple_grid/releases/tag/2.0.0 dann passen
