### ISSUE TITLE
Block Grids

### ISSUE THREAD

**Issue by saress** [DMAGmbH/dma_simple_grid#6]
Hi,

zuerst einmal herzlichen Dank für diese tolle Erweiterung!

Wäre es eventuell möglich, neben dem Flexgrid auch vielleicht
noch die Block Grids mit in die Feature Liste mit aufzunehmen?

Vielen Dank und beste Grüße
Saress

**Comment by JanoschOltmanns** [comment]
Meinst du die bsp. von Foundation (http://foundation.zurb.com/sites/docs/grid.html#block-grids)?

**Comment by saress** [comment]
Hallo Janosch,

ja genau, die meine ich.

Beste Grüße
Saress

PS: Sorry, hab versehentlich mal kurz den Issue geschlossen, falscher Knopf :-)

**Comment by JanoschOltmanns** [comment]
Gerne einmal im develop-Branch testen https://github.com/DMAGmbH/dma_simple_grid/tree/develop
