### ISSUE TITLE
Artikel-Ansicht

### ISSUE THREAD

**Issue by saress** [DMAGmbH/dma_simple_grid#7]
Hi,

mir ist aufgefallen, dass in der Artikel-Ansicht bei "DMA SimpleGrid (SimpleGrid: Column Start) links von den Bearbeitungssymbolen auch die gewählten Klassen angezeigt werden, also z.B. small-4 medium-centered, was natürlich sehr praktisch ist, weil man auf einen Blick erkennt, wie der Grid aufgebaut wurde.

Dazu 2 Anmerkungen: hat man viele Klassen, dann wird natürlich die Liste immer länger und hier kann es dann durchaus auch sein, dass dadurch in der Artikel-Ansicht das Layout ein wenig in Mitleidenschaft gezogen wird. Siehe nachfolgenden Screen:

![image](https://cloud.githubusercontent.com/assets/1481301/15564571/e224cc0e-2313-11e6-99cf-3a5d709f8a4e.png)

Eventuell könnte man das Problem mit einer Art Tooltip lösen?
Zudem wäre es vielleicht auch ganz interessant, wenn die ausgewählten Grid-Klassen auch beim Row-Element angezeigt werden würden und eventuell auch die CSS-ID/Klassen von Contao (Experten-Einstellungen) mit angezeigt werden würden (hier ebenfalls jeweils beim Row und auch beim Column Element).

Vielen Dank und beste Grüße
Saress

**Comment by JanoschOltmanns** [comment]
Gerne einmal im develop-Branch testen https://github.com/DMAGmbH/dma_simple_grid/tree/develop

**Comment by saress** [comment]
Hallo Janosch,

könnte man die selbst ergänzten CSS-Klassen (auch die von den Experten Einstellungen) auch noch bei den Row und jetzt neu beim Wrapper Element mit anzeigen? Dann würde mal wirklich auf den ersten Blick erkennen können, wie der Grid aufgebaut ist. Bei den Inhaltsementen funktioniert das mit dem Tooltipp schon mal bestens, vielen Dank!
