### ISSUE TITLE
Wrapper Content Element

### ISSUE THREAD

**Issue by saress** [DMAGmbH/dma_simple_grid#8]
Hi,

es wäre sehr praktisch, wenn es zusätzlich zum SimpleGrid: Row Start / Stop Content Element noch ein weiteres Element mit gleicher Funktionalität geben würde. Konkret ein zusätzliches Wrapper Element z. B. SimpleGrid: Wrapper Start / Stop, in das man dann das Grid wrappen kann.

```
<div class="my-wrapper">
    <div class="row">
       <div class="medium-6 columns"></div>
    </div>
</div>
```

Man müsste hier eigentlich nur in den Experten-Einstellungen Klassen und IDs vergeben können, weitere Features würde der Wrapper nicht benötigen. In der Artikel-Ansicht wäre es dann ideal, wenn diese Klassen und IDs dann auch wieder angezeigt werden würden (siehe auch #7 ).

Warum das Ganze?
Oftmals ist es nötig, das Grid in zusätzliche Wrapper zu packen, da man z.B. eine Fullsize-Wrapper benötigt und darin gerne mit dem Foundation Grid weiterarbeiten würde oder mit multiplen Backgrounds arbeitet etc. Klarerweise könnte man das auch mit einem HTML Element lösen, aber die Tatsache alleine, dass z. B. das SimpleGrid: Row Start Element auch gleichzeitig ein Stop Element mit anlegt und man das alles schön verschachteln kann, macht den Gedanken an ein Wrapper-Element mit gleicher Funktionalität sehr verführerisch :-)

Vielen Dank und beste Grüße
Saress

**Comment by JanoschOltmanns** [comment]
Gerne einmal im develop-Branch testen https://github.com/DMAGmbH/dma_simple_grid/tree/develop

**Comment by saress** [comment]
Hallo Janosch,

vielen Dank, das geht ja blitzschnell :-)

Wir haben den Dev-Branch gerade mal getestet. Der Block-Grid scheint ganz normal zu funktionieren, das Wrapper-Element taucht allerdings nicht bei den Content-Elementen auf.

Kannst Du Dir das bitte noch einmal kurz anschauen?

Besten Dank,
Saress

**Comment by JanoschOltmanns** [comment]
Hallo,

mit welchem Grid hast du es denn getestet? Es kann gut sein, dass ich es noch nicht für alle integriert habe. Wichtig ist auch, diesen Punkt in den Systemeinstellungen zu aktivieren.

**Comment by saress** [comment]
Hallo Janosch,

konkret mit dem Foundation Grid. In den Einstellungen haben wir alles angehakt, das Blockgrid und auch die erweiterten Zeilen- und Spaltenklassen sind auch aktiviert.

**Comment by JanoschOltmanns** [comment]
Welche Wrapper-Klassen erwartet ihr denn zu haben?

**Comment by saress** [comment]
Soweit ich das gesehen habe, hast Du die Templates:

ce_dma_simplegrid_wrapperstart.html5 und
ce_dma_simplegrid_wrapperstop.html5

ergänzt. Ich hätte also vermutet, dass ich ein neues CE anlegen kann, analog zum Row- bzw. 
Column-Element. Nur scheinen die Templates nicht als Elementtyp auf.

**Comment by saress** [comment]
Hier noch ein kurzer Screen zur Ergänzung:

![image](https://cloud.githubusercontent.com/assets/1481301/15648970/341a5382-266e-11e6-9c8d-e305d23cc4ae.png)

**Comment by JanoschOltmanns** [comment]
Klar. Das ist korrekt. Allerdings werden die Elemente erst dann zur Auswahl angezeigt, wenn sie per Config auch nötig sind. Du kannst es auch per DCA-Config, indem du bsp. `$GLOBALS['DMA_SIMPLEGRID_CONFIG']['foundation']['config']['hasWrapper'] = true;` setzt. Alternativ baue ich es direkt in die Erweiterung ein, sofern ich sinnvolle Vorauswahlen für Klassen (wie sie bsp. bei Bootstrap da sind) habe.

**Comment by saress** [comment]
Ah ok, an das hab ich jetzt natürlich auch nicht gedacht. Ich denke, das wäre vielleicht eine sinnvolle Ergänzung im Settings Dialog bei den jeweiligen Frameworks. Ich hab das jetzt mal in der initconfig.php entsprechend ergänzt und die Templates sind alle da, perfekt.

An dieser Stelle noch einmal ein herzliches Dankeschön für diese tolle Erweiterung!

Vielen Dank
Saress
