### ISSUE TITLE
Flexbox Grid "Gridlex"  -> verschachtelte Klassennamen

### ISSUE THREAD

**Issue by sascha-mueller** [DMAGmbH/dma_simple_grid#9]
Hallo Janosch,
wie gerade besprochen möchte ich Dich bitten die Konfiguration so zu erweitern, dass das Flexbox-Grid "Gridlex" (http://gridlex.devlint.fr/) eingebaut werden kann.

Der Aufbau der Klassen ist hier teils wie folgt: col-6_md-12

Dies gilt sowohl für die "rows" wie auch für die "cols".

Ein Beispiel ist auch hier zu finden:
http://gridlex.devlint.fr/cards.html

**Comment by JanoschOltmanns** [comment]
Ist im develop-Branch zum testen https://github.com/DMAGmbH/dma_simple_grid/tree/develop

**Comment by sascha-mueller** [comment]
Hab den Eindruck, dass weitere Verschachtelungen für die Inhaltselemente nicht übernommen werden.

zB: "ce_text col-12_lg-8_md-6_sm-3_xs-1"

Ein weiteres Feld _md-8 hat er bei der Kassengenerierung einfach ignoriert.

Bei den Zeilenwrappern (SimpleGrid: Row Start) werden diese hingegen ausgewertet.

**Comment by JanoschOltmanns** [comment]
Leider verstehe ich nicht genau, was du meinst ;)

**Comment by JanoschOltmanns** [comment]
Da war noch ein Fehler in der Config-Datei. Habe es gerade mal angepasst.
